# Generated by Django 5.1.7 on 2025-03-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_remove_product_favorites"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_products",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_products", to="products.product"
            ),
        ),
    ]
