# Generated by Django 5.1.7 on 2025-04-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
