# Generated by Django 5.1.7 on 2025-04-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_category_image_url_product_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
    ]
