# Generated by Django 5.1.7 on 2025-03-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                choices=[("Pickup", "Pickup"), ("Delivery", "Delivery")],
                default="Pickup",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="full_name",
            field=models.CharField(default="Unknown", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("credit_card", "Credit Card"),
                    ("paypal", "PayPal"),
                    ("in_cash", "In Cash"),
                ],
                default="credit_card",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="phone_number",
            field=models.CharField(default="0000000000", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="pickup_address",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
