# Generated by Django 5.1.7 on 2025-04-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_stripe_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('in_cash', 'In Cash'), ('cart', 'Cart')], max_length=20),
        ),
    ]
